### PR TITLE
Ratelimiter Interface and mutex

### PR DESCRIPTION
**Pull request by gempir**
- the Ratelimiter could be called multiple times when used by multiple clients #171 
- Use an interface instead so anyone can provide Ratelimiter

### CODE REVIEW

**Comment by gempir** [comment]
@TroyDota if you wanna have a look

**Comment by TroyDota** [comment]
Looks great!
Exactly what I was thinking.

**Comment by TroyDota** [comment]
The only thing that is concerning is that you sleep and then unlock the mutex.

**Comment by gempir** [comment]
Why is that concerning? That's the correct moment to unlock the mutex, no?

**Review by pajlada — APPROVED** [review]
Looks good to me

Would like to understand @TroyDota's concern with the sleep/mutex unlock order but happy to take that offline since a new release won't be made instantly after this PR

**Comment by gempir** [comment]
image

I think how we do it here is perfectly fine

**Pull request merged**
