### PR TITLE
move test sources and run join in a gouroutine

### LINKED ISSUE #10: Connection not becoming active
The message

`:tmi.twitch.tv 001 justinfan123123 :Welcome, GLHF!` is somehow not evaluated correctly because Strings.HasPrefix doesn't work on the raw message. Strings.Contains works. Something with the PR #7 must have caused this.

https://github.com/gempir/go-twitch-irc/blob/master/client.go#L120

Pushing a quickfix with Strings.Contains for now

We should do some tests that actually connect to twitch, or need to improve our Mock

### PR DESCRIPTION
**Pull request by gempir**
@VitorFalcao this is what I had in mind.

Fixes #10 and #9 

The tests should be refactored seperately.

### CODE REVIEW

**Comment by VitorFalcao** [comment]
@gempir Oh, ok. I am sorry. I understood it wrong. I will update my fork according to the current master and work on the test's refactoring, then.

**Comment by VitorFalcao** [comment]
@gempir How would a user send a message? Because it is not possible to call `client.Say()`, since the code will be blocked at the `Connect()` call. It is possible to receive messages, but I don't see a way to send messages.

**Comment by gempir** [comment]
Users themselves can run Connect in a goroutine, but it's their choice. If they don't want to they can just run the program like the example and just listen

**Comment by VitorFalcao** [comment]
Oh, ok. Shouldn't we make that clear in the README?

**Comment by gempir** [comment]
No I think this is fine.

**Pull request merged**
