### PR TITLE
Add mod/vip/broadcaster fields to User

### PR DESCRIPTION
**Pull request by douglascdev**
Add mod/vip/broadcaster fields to User(#203)

### CODE REVIEW

**Comment by douglascdev** [comment]
Umm, maybe that linter should have an exception for test code?

**Comment by gempir** [comment]
> Umm, maybe that linter should have an exception for test code?

No, but you can disable that lint for that function name with a comment IMO

**Comment by douglascdev** [comment]
Limiting tests to just 100 lines seems more annoying than helpful to me but alright, I just cut some lines my specific test didn't need. Should be good to go now :+1:

**Review by gempir — APPROVED** [review]

**Comment by gempir** [comment]
Thank you for the contribution!

**Pull request merged**
